name: CI/CD to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 642570498889.dkr.ecr.us-east-1.amazonaws.com

    - name: Build & Push Image
      run: |
        docker build -t hospital-website .
        docker tag hospital-website:latest 642570498889.dkr.ecr.us-east-1.amazonaws.com/hospital-website:latest
        docker push 642570498889.dkr.ecr.us-east-1.amazonaws.com/hospital-website:latest

    - name: Deploy to EC2 (k3s)
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/hospitalmanagement
          sudo kubectl apply -f k8s/deployment.yaml
